name: Core/Test
on:
  push:

jobs:
  units:
    name: Units
    if: github.repository == 'opf/openproject'
    runs-on: [self-hosted,public]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v2
      with:
        path: /tmp/${{ github.sha }}
        key: ${{ runner.os }}-core-tests
    - name: test
      env:
        CI_JOBS: 16
        CI_CACHE_PATH: "/tmp/${{ github.sha }}/"
        LOCAL_DEV_CHECK: 1
        CI_RETRY_COUNT: 3
      run: |
        cp .env.example .env
        docker-compose -f docker-compose.ci.yml build ci
        docker-compose -f docker-compose.ci.yml run ci setup-tests run-units
    - name: cleanup
      if: ${{ always() }}
      run: docker-compose -f docker-compose.ci.yml down --remove-orphans -t 10
  features:
    needs: units
    name: Features
    if: github.repository == 'opf/openproject'
    runs-on: [self-hosted,public]
    timeout-minutes: 200
    steps:
    - uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v2
      with:
        path: /tmp/${{ github.sha }}
        key: ${{ runner.os }}-core-tests
    - name: test
      env:
        CI_JOBS: 16
        CI_CACHE_PATH: "/tmp/${{ github.sha }}/"
        LOCAL_DEV_CHECK: 1
        CI_RETRY_COUNT: 3
      run: |
        cp .env.example .env
        docker-compose -f docker-compose.ci.yml build ci
        docker-compose -f docker-compose.ci.yml run ci setup-tests run-features
    - name: cleanup
      if: ${{ always() }}
      run: docker-compose -f docker-compose.ci.yml down --remove-orphans -t 10
